const express = require('express');
const path = require('path');
const fs = require('fs');
const dotenv = require('dotenv');
const { Solar, Lunar } = require('lunar-javascript');

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 8080;

app.use(express.json());
// Serve static frontend files
app.use(express.static(__dirname));

const USERS_FILE = path.join(__dirname, 'users.json');

// Helper: Read users database
function readUsers() {
    if (!fs.existsSync(USERS_FILE)) {
        fs.writeFileSync(USERS_FILE, '[]', 'utf8');
        return [];
    }
    try {
        return JSON.parse(fs.readFileSync(USERS_FILE, 'utf8'));
    } catch (e) {
        console.error("Error reading users:", e);
        return [];
    }
}

// Helper: Write users database
function writeUsers(users) {
    try {
        fs.writeFileSync(USERS_FILE, JSON.stringify(users, null, 4), 'utf8');
    } catch (e) {
        console.error("Error writing users:", e);
    }
}

// Helper: Calculate Bazi & elements
function calculateBazi(dob, tob) {
    const date = new Date(dob);
    const hour = tob === 'unknown' ? 12 : parseInt(tob);
    const solar = Solar.fromYmdHms(date.getFullYear(), date.getMonth() + 1, date.getDate(), hour, 0, 0);
    const lunar = solar.getLunar();
    
    // BaZi contains [yearPillar, monthPillar, dayPillar, hourPillar]
    const pillars = lunar.getBaZi(); 
    const elements = lunar.getBaZiWuXing();
    const dayMasterElement = elements[2][0]; // Day Master Stem element (金/木/水/火/土)
    
    return {
        pillars,
        elements,
        dayMasterElement
    };
}

// Helper: Daily Fortune generator based on lunar algorithm
function getDailyFortuneData(dateStr, dob, tob) {
    const parts = dateStr.split('-');
    const year = parseInt(parts[0]);
    const month = parseInt(parts[1]);
    const day = parseInt(parts[2]);
    const solar = Solar.fromYmd(year, month, day);
    const lunar = solar.getLunar();
    
    const ganzhi = lunar.getDayInGanZhi(); // e.g. "乙未"
    const stem = ganzhi[0];
    const branch = ganzhi[1];
    const nayin = lunar.getDayNaYin(); // e.g. "沙中金"
    
    const yi = lunar.getDayYi(); 
    const ji = lunar.getDayJi(); 
    
    let score = "中"; 
    let theme = "踏实稳健，静观其变";
    let detailsZh = "今日流日磁场温和，适合稳健前行，凡事不宜操之过急。";
    let detailsEn = "Today's energy is gentle and stable. Suitable for steady progress, avoid rushing.";
    
    if (dob) {
        const bazi = calculateBazi(dob, tob);
        const dm = bazi.dayMasterElement; // e.g. "金", "木"...
        const dayWuXing = lunar.getBaZiWuXing()[2][0]; // day pillar element, e.g. "木"
        
        const relations = {
            '金': { generates: '水', generatedBy: '土', overcomes: '木', overcomeBy: '火' },
            '木': { generates: '火', generatedBy: '水', overcomes: '土', overcomeBy: '金' },
            '水': { generates: '木', generatedBy: '金', overcomes: '火', overcomeBy: '土' },
            '火': { generates: '土', generatedBy: '木', overcomes: '金', overcomeBy: '水' },
            '土': { generates: '金', generatedBy: '火', overcomes: '水', overcomeBy: '木' }
        };
        
        if (dm === dayWuXing) {
            score = "高";
            theme = "比劫同气，贵人相助";
            detailsZh = `今日流日五行为${dayWuXing}，与您的日元属性相同。同气相求，贵人缘佳，适合与团队合作或联络故友，行事顺遂。`;
            detailsEn = `Today's element is ${dayWuXing}, matching your Day Master. Great harmony and helper energy. Excellent for teamwork or connecting with friends.`;
        } else if (relations[dm].generatedBy === dayWuXing) {
            score = "高";
            theme = "印星生身，福泽连绵";
            detailsZh = `今日流日五行为${dayWuXing}，生助您的日元。印星庇护，精神饱满，利于学习、思考与修整，能得长辈关照。`;
            detailsEn = `Today's element ${dayWuXing} generates your Day Master. Blessed by guardian stars, optimal for studying, reflection, and receiving wisdom.`;
        } else if (relations[dm].overcomes === dayWuXing) {
            score = "高";
            theme = "财星高照，求财得利";
            detailsZh = `今日流日五行为${dayWuXing}，为您所克之财。财星主动，求财欲望增强，商务洽谈或投资决策容易获得正向收益。`;
            detailsEn = `Today's element ${dayWuXing} is controlled by your Day Master, indicating wealth star activation. Opportunities for financial growth and negotiation are favored.`;
        } else if (relations[dm].overcomeBy === dayWuXing) {
            score = "低";
            theme = "官杀克身，宜静不宜动";
            detailsZh = `今日流日五行为${dayWuXing}，克制您的日元。压力偏重，情绪容易产生波动，建议低调行事，注意身体健康与作息。`;
            detailsEn = `Today's element ${dayWuXing} counters your Day Master. Pressure may increase, keep a low profile, protect your energy, and avoid arguments.`;
        } else {
            score = "中";
            theme = "食伤泄秀，展现才华";
            detailsZh = `今日流日五行为${dayWuXing}，为您所生之食伤。思维活跃，才华横溢，利于创意与表达，但要防口舌之争。`;
            detailsEn = `Today's element ${dayWuXing} is generated by your Day Master. Your creativity is high, excellent for artistic output or project brainstorming.`;
        }
    }
    
    return {
        ganzhi,
        stem,
        branch,
        nayin,
        luck: score,
        theme,
        yi: yi.slice(0, 3), 
        ji: ji.slice(0, 3),
        details: {
            zh: detailsZh,
            en: detailsEn
        }
    };
}

// Helper: Generate Mock Bazi Detailed Reports
function generateDetailedReport(userData, baziData) {
    const name = userData.fullname;
    const dm = baziData.dayMasterElement;
    
    return {
        wuxing: {
            title: "五行的分布与流通",
            title_en: "Five Elements Distribution & Flow",
            content_zh: `<h3>五行能量分布分析</h3>
                         <p>命主<strong>${name}</strong>的日元属<strong>${dm}</strong>。经排盘推演，其命局五行分布为：
                         金：${baziData.elements.filter(e => e.includes('金')).length}个，
                         木：${baziData.elements.filter(e => e.includes('木')).length}个，
                         水：${baziData.elements.filter(e => e.includes('水')).length}个，
                         火：${baziData.elements.filter(e => e.includes('火')).length}个，
                         土：${baziData.elements.filter(e => e.includes('土')).length}个。</p>
                         <p>整体格局呈现能量流动。当前大运与流年磁场交汇，建议多接触互补五行对应的生活习惯进行能量调和。</p>`,
            content_en: `<h3>Elemental Balance Quantification</h3>
                         <p>Client <strong>${name}</strong>'s Day Master is <strong>${dm}</strong>. The elemental distribution in the natal chart shows:
                         Metal: ${baziData.elements.filter(e => e.includes('金')).length}, 
                         Wood: ${baziData.elements.filter(e => e.includes('木')).length}, 
                         Water: ${baziData.elements.filter(e => e.includes('水')).length}, 
                         Fire: ${baziData.elements.filter(e => e.includes('火')).length}, 
                         Earth: ${baziData.elements.filter(e => e.includes('土')).length}.</p>
                         <p>To enhance cosmic alignment, balancing deficient elements through environment layout is highly recommended.</p>`
        },
        yongshen: {
            title: "用神与忌神",
            title_en: "Favorable & Unfavorable Elements",
            content_zh: `<h3>喜忌神详批</h3>
                         <p>根据《渊海子平》身强身弱判定：本命以<strong>${dm === '木' || dm === '水' ? '金' : '木'}</strong>为用神，以<strong>${dm === '火' || dm === '土' ? '水' : '土'}</strong>为忌神。</p>
                         <p><strong>用神（Yong Shen）</strong>代表命局的枢纽与解药。在用神岁运中，命主心境开朗，事业财富极易突破瓶颈。<strong>忌神（Ji Shen）</strong>则代表压力与阻碍，逢忌神流年需低调收敛，防范损财。</p>`,
            content_en: `<h3>Yong Shen & Ji Shen Analysis</h3>
                         <p>Based on classic Bazi balancing rules, your Favorable Element (Yong Shen) is determined to be <strong>${dm === '木' || dm === '水' ? 'Metal' : 'Wood'}</strong>, and your Unfavorable Element (Ji Shen) is <strong>${dm === '火' || dm === '土' ? 'Water' : 'Earth'}</strong>.</p>
                         <p>Activating your Favorable Element via lifestyle adjustments will significantly boost your fortune, while caution should be exercised during seasons dominated by your Unfavorable Element.</p>`
        },
        career: {
            title: "红包 | 事业财富",
            title_en: "Career & Wealth Fortune",
            content_zh: `<h3>一生财运官运轨迹</h3>
                         <p>命盘中财星暗藏，代表一生财富多为“大器晚成”之象。正财稳健，适合在专业领域深耕；偏财星弱，不宜投机性强的金融博弈。</p>
                         <p>用神为${dm === '木' || dm === '水' ? '金' : '木'}，最适合从事与之相关的行业。中年以后行运好转，财库大开，有白手起家、稳步晋升的极佳机缘。</p>`,
            content_en: `<h3>Career Path & Financial Lifeline</h3>
                         <p>Your chart contains active Direct Wealth stars, suggesting stable, long-term asset accumulation through professional mastery. Speculative or high-risk investments should be avoided.</p>
                         <p>Aligning your job with industries associated with your Favorable Element will unlock rapid promotions and financial security, especially during your 30s and 40s.</p>`
        },
        marriage: {
            title: "同心锁 | 婚姻感情",
            title_en: "Love & Spouse Palace",
            content_zh: `<h3>夫妻宫与桃花羁绊</h3>
                         <p>本命夫妻宫坐守吉星，代表配偶性格温和，在事业或生活中对您有极大助益。男女命盘中桃花星适中，异性缘佳，但要防范情感摩擦。</p>
                         <p>婚姻美满期通常在流年逢合的年份。若未婚，未来两年内（特别是流年逢六合、三合之年）将迎来正缘桃花，宜积极把握相识良机。</p>`,
            content_en: `<h3>Romantic Harmony & Marriage Palace</h3>
                         <p>The Spouse Palace in your birth chart is populated by auspicious auxiliary stars, indicating a supportive, loyal, and intelligent life partner who brings peace and stability.</p>
                         <p>For single individuals, cosmic alignments in the upcoming 12-24 months show a high probability of meeting your destiny partner. Nurture these connections with patience.</p>`
        },
        growth: {
            title: "文昌笔 | 学习成长",
            title_en: "Education & Growth",
            content_zh: `<h3>智力启迪与自我修养</h3>
                         <p>文昌贵人高悬，命主天资聪颖，心思缜密。学习能力强，适合深造，考运极佳。一生乐于钻研，多才多艺，常在学术或文化创意领域展现过人天赋。</p>
                         <p>建议日常多阅读经典，修身养性，能够冲破精神瓶颈，达到更高的境界。</p>`,
            content_en: `<h3>Intellectual Talents & Spiritual Growth</h3>
                         <p>Blessed by the Wen Chang (Academic) star, you possess a sharp, analytical mind and high curiosity. You learn complex concepts quickly and have strong exam luck.</p>
                         <p>Continued learning, writing, or teaching are powerful channels to express your inner genius and achieve spiritual satisfaction.</p>`
        },
        health: {
            title: "平安符 | 身体健康",
            title_en: "Health & Vitality",
            content_zh: `<h3>五行脏腑调理指引</h3>
                         <p>本命局中，由于五行中${dm === '金' ? '木气' : '金气'}较弱，需特别注意与之相关的脏腑保养。金主肺、大肠，木主肝、胆，土主脾、胃，水主肾、膀胱，火主心、小肠。</p>
                         <p>作息应当顺应四时变化，多进行户外有氧运动，合理膳食以养元气。</p>`,
            content_en: `<h3>Elemental Health Alignment</h3>
                         <p>With an imbalance where ${dm === '金' ? 'Wood' : 'Metal'} is deficient, close attention should be paid to liver/gallbladder or lung/respiratory systems respectively.</p>
                         <p>Maintaining a balanced lifestyle with regular sleep patterns, natural organic diet, and light exercise will strengthen your immune field.</p>`
        },
        annual2026: {
            title: "2026丙午年运书",
            title_en: "2026 BingWu Annual Flow Book",
            content_zh: `<h3>2026丙午年流年大势详批</h3>
                         <p>2026为丙午流年，天干为丙火，地支为午火，乃是极旺之火运。火主礼、主光明、主爆发。</p>
                         <p>对于日元为<strong>${dm}</strong>的命主来说：
                         ${dm === '金' ? '火来克金，官杀重重。今年职场上面临重大转型与责任加码，挑战与机遇并存，需防犯小人，稳字当头。' : ''}
                         ${dm === '木' ? '木来生火，食伤泄秀。今年创意涌现，是开拓事业、展现才华的绝佳年份，但需注意防范身心过劳。' : ''}
                         ${dm === '水' ? '水来克火，水火既济。财官交汇，利于商务拓展、买房置业，情感上有正缘牵线，生活迎来转折。' : ''}
                         ${dm === '火' ? '火火相遇，比劫争财。今年竞争激烈，切忌盲目投资或合伙创业，凡事应保守沉着，保本为上。' : ''}
                         ${dm === '土' ? '火来生土，印星高照。今年运势顺遂，有贵人扶持，房产运或学业考运极佳，适合安心谋求长远规划。' : ''}
                         </p>
                         <p>建议在年中（特别是夏季火旺之时）保持冷静克制，避免做冲动决策。宜佩戴吉祥物或调和方位，方可乘风破浪，趋吉避凶。</p>`,
            content_en: `<h3>2026 BingWu Annual Forecast</h3>
                         <p>2026 is the year of BingWu (Fire Horse), bringing intense, radiant Fire energy globally, governing passion, digital growth, and fast transformations.</p>
                         <p>For your Day Master <strong>${dm}</strong>, this means:
                         ${dm === '金' ? 'Fire counters Metal. High career shifts and responsibility increases are expected. Exercise patience, protect health, and avoid workplace friction.' : ''}
                         ${dm === '木' ? 'Wood feeds Fire. High creative output and entrepreneurial opportunities appear. Express your talents boldly, but guard against burnout.' : ''}
                         ${dm === '水' ? 'Water controls Fire. Excellent opportunities for business development, asset acquisition, and romantic milestones. Balance fire with calm reflection.' : ''}
                         ${dm === '火' ? 'Fire joins Fire. High competition. Guard against impulsive partnerships or quick investments. Prioritize risk management.' : ''}
                         ${dm === '土' ? 'Fire feeds Earth. Strong support from mentors, high academic luck, and property stability. A beautiful year to consolidate and plan.' : ''}
                         </p>
                         <p>Focus on maintaining mental peace during summer months when fire peaks. Aligning your schedule will attract good fortune throughout 2026.</p>`
        }
    };
}

// Expose configuration to frontend
app.get('/api/config', (req, res) => {
    return res.json({
        googleClientId: process.env.GOOGLE_CLIENT_ID || ""
    });
});

// 1. API: Auth Register
app.post('/api/auth/register', (req, res) => {
    try {
        const { username, password, fullname, gender, dob, tob } = req.body;
        if (!username || !password || !fullname || !gender || !dob || !tob) {
            return res.status(400).json({ error: "请填写所有必填注册字段。" });
        }

        const users = readUsers();
        const exists = users.find(u => u.username === username);
        if (exists) {
            return res.status(400).json({ error: "该用户名已被注册。" });
        }

        const newUser = {
            username,
            password,
            fullname,
            gender,
            dob,
            tob,
            tier: 'free',
            chatCount: 0,
            registeredAt: new Date().toISOString()
        };

        users.push(newUser);
        writeUsers(users);

        return res.json({ success: true, user: { username: newUser.username, fullname: newUser.fullname, tier: newUser.tier } });
    } catch (e) {
        console.error("Register error:", e);
        return res.status(500).json({ error: "服务器内部注册错误。" });
    }
});

// 2. API: Auth Login
app.post('/api/auth/login', (req, res) => {
    try {
        const { username, password } = req.body;
        if (!username || !password) {
            return res.status(400).json({ error: "用户名及密码不可为空。" });
        }

        const users = readUsers();
        const user = users.find(u => u.username === username && u.password === password);
        if (!user) {
            return res.status(401).json({ error: "用户名或密码错误。" });
        }

        return res.json({ success: true, user: { username: user.username, fullname: user.fullname, tier: user.tier } });
    } catch (e) {
        console.error("Login error:", e);
        return res.status(500).json({ error: "服务器内部登录错误。" });
    }
});

// Google Authentication Check
app.post('/api/auth/google', async (req, res) => {
    try {
        const { googleId, email, accessToken } = req.body;
        
        let targetGoogleId = googleId;
        let targetEmail = email;
        let targetName = "";

        if (accessToken) {
            // Real OAuth verification: query Google userinfo API
            try {
                const googleRes = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', {
                    headers: { 'Authorization': `Bearer ${accessToken}` }
                });
                if (!googleRes.ok) {
                    const errText = await googleRes.text();
                    console.error("Failed to verify Google access token:", errText);
                    return res.status(400).json({ error: "Invalid Google access token." });
                }
                const profile = await googleRes.json();
                targetGoogleId = profile.sub;
                targetEmail = profile.email;
                targetName = profile.name || profile.given_name || "";
            } catch (err) {
                console.error("Error verifying access token with Google:", err);
                return res.status(502).json({ error: "Unable to verify credentials with Google." });
            }
        }

        if (!targetGoogleId || !targetEmail) {
            return res.status(400).json({ error: "Missing googleId, email, or accessToken." });
        }

        const users = readUsers();
        let user = users.find(u => u.googleId === targetGoogleId || (u.email && u.email === targetEmail));
        if (user) {
            // Update googleId if matched by email and not set yet
            if (!user.googleId) {
                user.googleId = targetGoogleId;
                writeUsers(users);
            }
            return res.json({
                success: true,
                exists: true,
                user: { username: user.username, fullname: user.fullname, tier: user.tier }
            });
        }

        return res.json({ 
            success: true, 
            exists: false, 
            profile: { 
                googleId: targetGoogleId, 
                email: targetEmail, 
                name: targetName 
            } 
        });
    } catch (e) {
        console.error("Google auth check error:", e);
        return res.status(500).json({ error: "Internal server error during Google auth check." });
    }
});

// Google Authentication Register
app.post('/api/auth/google-register', (req, res) => {
    try {
        const { googleId, email, name, fullname, gender, dob, tob } = req.body;
        if (!googleId || !email || !fullname || !gender || !dob || !tob) {
            return res.status(400).json({ error: "请填写所有必填注册及八字字段。" });
        }

        const users = readUsers();
        let user = users.find(u => u.googleId === googleId || (u.email && u.email === email));
        if (user) {
            return res.status(400).json({ error: "该 Google 账号已被关联。" });
        }

        let cleanEmailPrefix = email.split('@')[0].replace(/[^a-zA-Z0-9]/g, '');
        let username = `g_${cleanEmailPrefix}`;
        let counter = 1;
        let baseUsername = username;
        while (users.some(u => u.username === username)) {
            username = `${baseUsername}_${counter}`;
            counter++;
        }

        const newUser = {
            username,
            email,
            googleId,
            password: `g_pass_${googleId}`,
            fullname,
            gender,
            dob,
            tob,
            tier: 'free',
            chatCount: 0,
            registeredAt: new Date().toISOString()
        };

        users.push(newUser);
        writeUsers(users);

        return res.json({ success: true, user: { username: newUser.username, fullname: newUser.fullname, tier: newUser.tier } });
    } catch (e) {
        console.error("Google register error:", e);
        return res.status(500).json({ error: "服务器内部 Google 注册错误。" });
    }
});

// 3. API: Get Profile & Bazi Calculation
app.get('/api/user/profile', (req, res) => {
    try {
        const { username } = req.query;
        if (!username) {
            return res.status(400).json({ error: "Missing username parameter." });
        }

        const users = readUsers();
        const user = users.find(u => u.username === username);
        if (!user) {
            return res.status(404).json({ error: "User not found." });
        }

        const bazi = calculateBazi(user.dob, user.tob);
        return res.json({
            success: true,
            user: {
                username: user.username,
                fullname: user.fullname,
                gender: user.gender,
                dob: user.dob,
                tob: user.tob,
                tier: user.tier
            },
            bazi
        });
    } catch (e) {
        console.error("Profile query error:", e);
        return res.status(500).json({ error: "Internal profile retrieval error." });
    }
});

// 4. API: Daily Fortune Calculations
app.get('/api/daily-fortune', (req, res) => {
    try {
        const { date, dob, tob } = req.query;
        if (!date) {
            return res.status(400).json({ error: "Missing date parameter (YYYY-MM-DD)." });
        }
        
        const fortune = getDailyFortuneData(date, dob, tob);
        return res.json({ success: true, fortune });
    } catch (e) {
        console.error("Daily fortune error:", e);
        return res.status(500).json({ error: "Internal calendar prediction error." });
    }
});

// 5. API: Get Destiny Detailed Reports (locked vs unlocked)
app.get('/api/bazi-report', (req, res) => {
    try {
        const { username } = req.query;
        if (!username) {
            return res.status(400).json({ error: "Missing username parameter." });
        }

        const users = readUsers();
        const user = users.find(u => u.username === username);
        if (!user) {
            return res.status(404).json({ error: "User not found." });
        }

        const bazi = calculateBazi(user.dob, user.tob);
        const reportData = generateDetailedReport(user, bazi);

        // If user is not master, return locked/restricted payload
        if (user.tier !== 'master') {
            return res.json({
                success: true,
                unlocked: false,
                message: "This report is locked. Please upgrade to Master membership.",
                bazi: {
                    pillars: bazi.pillars,
                    elements: bazi.elements,
                    dayMasterElement: bazi.dayMasterElement
                }
            });
        }

        // Return fully unlocked reports
        return res.json({
            success: true,
            unlocked: true,
            bazi,
            reports: reportData
        });
    } catch (e) {
        console.error("Report generation error:", e);
        return res.status(500).json({ error: "Failed to generate report." });
    }
});

// 6. API: AI Divination Consultation Chat (Limited for Free users)
app.post('/api/chat/message', async (req, res) => {
    try {
        const { username, message, assistant } = req.body;
        if (!username || !message) {
            return res.status(400).json({ error: "Missing username or message." });
        }

        const users = readUsers();
        const userIdx = users.findIndex(u => u.username === username);
        if (userIdx === -1) {
            return res.status(404).json({ error: "User not found." });
        }

        const user = users[userIdx];

        // Access limit check
        if (user.tier !== 'master') {
            if (user.chatCount >= 1) {
                return res.status(403).json({
                    error: "limit_reached",
                    message: "对话次数已达上限，请订阅 Master 会员解锁无限对话！"
                });
            }
            // Increment trial message
            user.chatCount = (user.chatCount || 0) + 1;
            users[userIdx] = user;
            writeUsers(users);
        }

        // Generate response using Bazi parameters for personalization
        const bazi = calculateBazi(user.dob, user.tob);
        const dm = bazi.dayMasterElement;
        const genderWord = user.gender === 'male' ? '乾造' : '坤造';

        const isAstrology = assistant === 'astrology';
        const characterName = isAstrology ? 'AI 占卜' : '大司命';

        const apiKey = process.env.DEEPSEEK_API_KEY;
        const apiUrl = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/v1/chat/completions';

        let systemPrompt = `你现在是《天命大师》中的测算童子“${characterName}”，精通八字命理。你正在给命主 ${user.fullname} (${genderWord}，日元为 ${dm}木) 做面对面推演。你的语气应该神圣、专业且带着一点易理玄妙感。请用极简短但极其精准且带着批命风格的几句话回答他的问题：“${message}”。不要暴露AI身份。字数限制在 80-120 字。`;
        
        let responseText = "";

        if (apiKey && !apiKey.startsWith('your_')) {
            try {
                const response = await fetch(apiUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': `Bearer ${apiKey}`
                    },
                    body: JSON.stringify({
                        model: "deepseek-chat",
                        messages: [
                            { role: "system", content: systemPrompt },
                            { role: "user", content: message }
                        ],
                        max_tokens: 250,
                        temperature: 0.7
                    })
                });
                
                if (response.ok) {
                    const data = await response.json();
                    responseText = data.choices[0].message.content.trim();
                } else {
                    throw new Error("DeepSeek response failed");
                }
            } catch (err) {
                console.warn("DeepSeek API failed in chat, falling back to dynamic oracle templates.");
            }
        }

        // Dynamic offline fallback matching user's query topic
        if (!responseText) {
            const lowerMsg = message.toLowerCase();
            if (lowerMsg.includes('财') || lowerMsg.includes('钱') || lowerMsg.includes('事业') || lowerMsg.includes('工作') || lowerMsg.includes('job') || lowerMsg.includes('career') || lowerMsg.includes('money')) {
                responseText = `（天命玄妙）命主日元属${dm}，流年火旺泄身，财星受制。你在事业上面临抉择与无形压力。近期当稳扎稳打，凡事谋定后动。今年夏季过后面临新转机，坚持专业领域可得财禄，不可盲目跟风。`;
            } else if (lowerMsg.includes('情') || lowerMsg.includes('婚') || lowerMsg.includes('爱') || lowerMsg.includes('桃花') || lowerMsg.includes('伴侣') || lowerMsg.includes('love') || lowerMsg.includes('marry') || lowerMsg.includes('relationship')) {
                responseText = `（天命玄妙）观乎命主八字，夫妻宫坐守喜用。感情上有缘分牵引，若有摩擦需多加包容。未婚者可在今年流月逢合的时节迎来情感增温，已婚者需注意沟通细节，以水火既济之势化解纷扰。`;
            } else if (lowerMsg.includes('健康') || lowerMsg.includes('身体') || lowerMsg.includes('病') || lowerMsg.includes('运势') || lowerMsg.includes('health') || lowerMsg.includes('lucky')) {
                responseText = `（天命玄妙）日主${dm}受流年磁场冲洗，火气炎上克金。注意作息起居，多补充与用神相和的绿色或水性食物。调养好五行脏腑，则精神内敛，邪气不侵，自身运势自能蒸蒸日上。`;
            } else {
                responseText = `（天命玄妙）命主 ${user.fullname} 询问此卦。八字格局之中，日元${dm}在流日遇动。所问之事虚实交错，应当心平气静。退一步海阔天空，在顺应五行流转的规律下，耐心等待自可拨云见日。`;
            }
        }

        return res.json({
            success: true,
            reply: responseText,
            remainingCount: user.tier === 'master' ? -1 : 0
        });
    } catch (e) {
        console.error("Chat message error:", e);
        return res.status(500).json({ error: "Failed to generate chat response." });
    }
});

// 7. API: Simulate Webhook Subscription Complete
app.post('/api/subscribe/simulate', (req, res) => {
    try {
        const { username } = req.body;
        if (!username) {
            return res.status(400).json({ error: "Username is required." });
        }

        const users = readUsers();
        const idx = users.findIndex(u => u.username === username);
        if (idx === -1) {
            return res.status(404).json({ error: "User not found." });
        }

        users[idx].tier = 'master';
        writeUsers(users);

        console.log(`[Subscription simulated] User ${username} unlocked all Bazi modules and annual book.`);
        return res.json({
            success: true,
            user: {
                username: users[idx].username,
                fullname: users[idx].fullname,
                tier: users[idx].tier
            }
        });
    } catch (e) {
        console.error("Simulation error:", e);
        return res.status(500).json({ error: "Internal simulation webhook error." });
    }
});

// Fallback to serving index.html for undefined routes
app.get('*all', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, () => {
    console.log(`TianMing SaaS Server running securely on http://localhost:${PORT}`);
});
